"""
Django settings for youtora project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from enum import Enum
from os import path
from pathlib import Path

# start building the index
# Build paths inside the project like this: BASE_DIR / 'subdir'.
from elasticsearch_dsl.connections import connections

BASE_DIR = Path(__file__).resolve().parent.parent  # the base directory of this project
DATA_DIR = path.join(BASE_DIR, "data")  # the directory to put all the data

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(v0y^*1$@(=zn-ywn25rwxrhcnrh_wcpt*a*j$$avnpk7yb0iq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'youtora.home',  # just for.. hmm...
    'youtora.index',  # for indexing data to elasticsearch index.
    'youtora.collect',  # for scraping data from youtube
    'youtora.search',  # app for general search
    'youtora.refine'  # app for parsing
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# djongo connector setup tutorial: https://www.youtube.com/watch?v=iKB_4HWKMCc
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'youtora_db',
        'CLIENT': {
            'host': "mongodb://192.168.219.197:27017"
        }  # experiment with the local one
        # you may or may need username or password
        # experiment with the localhost first
        # MONGO_URI = "mongodb://localhost:27017"
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# elastic search dsl configuration.
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': '192.168.219.197:9200'
    },
}

# TODO better have all the es-related stuff to be defined here. (central access points).
ES_CLIENT = connections.create_connection(hosts=ELASTICSEARCH_DSL['default']['hosts'])


# index names are stored here.
class IndexName(Enum):
    GENERAL = "general_idx"
    OPENSUB = "opensub_idx"


# string formats to be used
STR_FORMATS = {
    'vid_url': "https://www.youtube.com/watch?v={}",
    'chan_url': "https://www.youtube.com/channel/{}",
    'chan_uploads_url': "https://m.youtube.com/channel/{}/videos?view=0&flow=list",
    'vid_timed_url': "https://youtu.be/{}?t={}"
}
