# Generated by Django 3.0.5 on 2020-10-21 12:43

import django.contrib.postgres.fields.jsonb
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRaw',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='channel_id')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('lang_code', models.CharField(max_length=10)),
                ('main_html', models.TextField()),
                ('uploads_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdiomRaw',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('wiktionary_url', models.CharField(max_length=100)),
                ('main_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TracksRaw',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False,
                                        verbose_name='caption_id|tracks_raw')),
                ('caption_id', models.CharField(max_length=100)),
                ('raw_xml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoRaw',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='video_id')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('video_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('main_html', models.TextField()),
                (
                    'channel_raw',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.ChannelRaw')),
            ],
        ),
    ]
