# Generated by Django 3.0.5 on 2020-10-28 12:35

import django.core.validators
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('lang_code', models.CharField(max_length=10)),
                ('main_html', models.TextField()),
                ('uploads_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdiomRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('wiktionary_url', models.CharField(max_length=100)),
                ('parser_info', djongo.models.fields.JSONField(blank=True, default=None)),
                ('main_html', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TracksRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('caption_id', models.CharField(max_length=100, unique=True)),
                ('raw_xml', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='VideoRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('video_info', djongo.models.fields.JSONField(default=None)),
                ('main_html', models.TextField()),
                ('channel_id', models.CharField(max_length=100)),
            ],
        ),
    ]
