# Generated by Django 3.0.5 on 2020-10-12 04:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import youtora.scrape.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='channel_id')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('lang_code', models.CharField(max_length=10)),
                ('main_html', models.TextField()),
                ('uploads_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MLGloss',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('ref', models.URLField(validators=[django.core.validators.URLValidator])),
                ('category', models.CharField(max_length=100)),
                ('desc', djongo.models.fields.EmbeddedField(model_container=youtora.scrape.models.MLGlossDesc)),
            ],
        ),
        migrations.CreateModel(
            name='TracksRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='caption_id|tracks_raw')),
                ('caption_id', models.CharField(max_length=100)),
                ('raw_xml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoRaw',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='video_id')),
                ('video_info', djongo.models.fields.JSONField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.ChannelRaw')),
            ],
        ),
    ]
