# Generated by Django 3.0.5 on 2020-10-22 07:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collect', '0002_auto_20201022_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiomraw',
            name='idiom_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
