# Generated by Django 3.0.5 on 2020-10-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collect', '0003_auto_20201022_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiomraw',
            name='main_html',
            field=models.TextField(default='', null=True),
        ),
    ]
