# Generated by Django 3.0.5 on 2020-10-22 11:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collect', '0004_idiomraw_main_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiomraw',
            old_name='idiom_info',
            new_name='parser_1_info',
        ),
        migrations.AddField(
            model_name='idiomraw',
            name='parser_2_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
