# Generated by Django 3.0.5 on 2020-10-22 11:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collect', '0006_auto_20201022_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiomraw',
            name='main_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idiomraw',
            name='parser_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
