# Generated by Django 3.0.5 on 2020-10-21 12:43

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('wiktionary_url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('defs',
                 django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(),
                                                           size=None)),
            ],
        ),
    ]
