# Generated by Django 3.0.5 on 2020-10-20 01:03

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import youtora.refine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('idiom', models.CharField(max_length=100)),
                ('wiktionary_url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('defs', djongo.models.fields.ArrayField(model_container=youtora.refine.models.IdiomDef)),
            ],
        ),
        migrations.CreateModel(
            name='MLGloss',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('ref', models.URLField(validators=[django.core.validators.URLValidator])),
                ('category', models.CharField(max_length=100)),
                ('desc', djongo.models.fields.EmbeddedField(model_container=youtora.refine.models.MLGlossDesc)),
            ],
        ),
    ]
