# Generated by Django 3.0.5 on 2020-10-26 12:05

import django.core.validators
import djongo.models.fields
from django.db import migrations, models

import youtora.refine.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('wiktionary_url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('senses', djongo.models.fields.ArrayField(blank=True, default=list,
                                                           model_container=youtora.refine.models.Sense)),
            ],
        ),
    ]
