# Generated by Django 3.0.5 on 2020-10-22 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('refine', '0003_auto_20201022_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiom',
            old_name='meanings',
            new_name='senses',
        ),
    ]
