# Generated by Django 3.0.5 on 2020-10-23 02:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('refine', '0005_auto_20201023_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiom',
            name='related_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True,
                                                            default=list, size=None),
        ),
        migrations.AlterField(
            model_name='idiom',
            name='senses',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True), blank=True, default=list,
                size=None),
        ),
    ]
